# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

import os
from azure.cli.testsdk import ScenarioTest
from azure.cli.testsdk import ResourceGroupPreparer
from .example_steps import step_marketplace_agreement_create
from .example_steps import step_monitor_create
from .example_steps import step_monitor_show
from .example_steps import step_monitor_list
from .example_steps import step_monitor_list2
from .example_steps import step_monitor_update
from .example_steps import step_api_key_get_default_key
from .example_steps import step_api_key_list
from .example_steps import step_api_key_set_default_key
from .example_steps import step_host_list
from .example_steps import step_linked_resource_list
from .example_steps import step_marketplace_agreement_list
from .example_steps import step_monitored_resource_list
from .example_steps import step_set_password_link_get
from .example_steps import step_sso_config_create
from .example_steps import step_sso_config_show
from .example_steps import step_sso_config_list
from .example_steps import step_tag_rule_create
from .example_steps import step_tag_rule_show
from .example_steps import step_tag_rule_list
from .example_steps import step_monitor_delete
from .. import (
    try_manual,
    raise_if,
    calc_coverage
)


TEST_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '..'))


# Env setup_scenario
@try_manual
def setup_scenario(test, rg):
    pass


# Env cleanup_scenario
@try_manual
def cleanup_scenario(test, rg):
    pass


# Testcase: Scenario
@try_manual
def call_scenario(test, rg):
    setup_scenario(test, rg)
    step_marketplace_agreement_create(test, rg, checks=[])
    step_monitor_create(test, rg, checks=[
        test.check("name", "{myMonitor}", case_sensitive=False),
        test.check("sku.name", "free_Monthly", case_sensitive=False),
        test.check("location", "West US", case_sensitive=False),
        test.check("tags.Environment", "Dev", case_sensitive=False),
    ])
    step_monitor_show(test, rg, checks=[
        test.check("name", "{myMonitor}", case_sensitive=False),
        test.check("location", "West US", case_sensitive=False),
        test.check("tags.Environment", "Dev", case_sensitive=False),
    ])
    step_monitor_list(test, rg, checks=[
        test.check('length(@)', 1),
    ])
    step_monitor_list2(test, rg, checks=[
        test.check('length(@)', 1),
    ])
    step_monitor_update(test, rg, checks=[
        test.check("name", "{myMonitor}", case_sensitive=False),
        test.check("name", "{myMonitor}", case_sensitive=False),
        test.check("location", "West US", case_sensitive=False),
        test.check("tags.Environment", "Dev", case_sensitive=False),
    ])
    step_api_key_get_default_key(test, rg, checks=[])
    step_api_key_list(test, rg, checks=[])
    step_api_key_set_default_key(test, rg, checks=[])
    step_host_list(test, rg, checks=[])
    step_linked_resource_list(test, rg, checks=[])
    step_marketplace_agreement_list(test, rg, checks=[])
    step_monitored_resource_list(test, rg, checks=[])
    step_set_password_link_get(test, rg, checks=[])
    step_sso_config_create(test, rg, checks=[])
    step_sso_config_show(test, rg, checks=[])
    step_sso_config_list(test, rg, checks=[])
    step_tag_rule_create(test, rg, checks=[])
    step_tag_rule_show(test, rg, checks=[])
    step_tag_rule_list(test, rg, checks=[])
    step_monitor_delete(test, rg, checks=[])
    cleanup_scenario(test, rg)


# Test class for Scenario
@try_manual
class DatadogScenarioTest(ScenarioTest):

    def __init__(self, *args, **kwargs):
        super(DatadogScenarioTest, self).__init__(*args, **kwargs)
        self.kwargs.update({
            'myMonitor': 'myMonitor',
        })


    @ResourceGroupPreparer(name_prefix='clitestdatadog_myResourceGroup'[:7], key='rg', parameter_name='rg')
    def test_datadog_Scenario(self, rg):
        call_scenario(self, rg)
        calc_coverage(__file__)
        raise_if()

