# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum, EnumMeta
from six import with_metaclass

class _CaseInsensitiveEnumMeta(EnumMeta):
    def __getitem__(self, name):
        return super().__getitem__(name.upper())

    def __getattr__(cls, name):
        """Return the enum member matching `name`
        We use __getattr__ instead of descriptors or inserting into the enum
        class' __dict__ in order to support `name` and `value` being both
        properties for enum members (which live in the class' __dict__) and
        enum members themselves.
        """
        try:
            return cls._member_map_[name.upper()]
        except KeyError:
            raise AttributeError(name)


class ContractStatus(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Indicate if the contract is an editable Draft or a readonly Active contract
    """

    DRAFT = "Draft"
    ACTIVE = "Active"

class CreatedByType(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The type of identity that created the resource.
    """

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"

class DataMovementExecutionStage(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The stage of data movement
    """

    INPUT = "Input"
    OUTPUT = "Output"

class DataProcessingStrategy(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Data processing strategy to use for the the child DataSets
    """

    COPY_BASED = "CopyBased"
    IN_PLACE = "InPlace"

class Enum10(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):

    PRODUCTION = "Production"
    SAMPLE = "Sample"

class Enum8(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):

    PRODUCTION = "Production"
    SAMPLE = "Sample"

class Enum9(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):

    PRODUCTION = "Production"
    SAMPLE = "Sample"

class ExecutionStatus(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Execution status e.g. Success, Failed, InProgress
    """

    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    IN_PROGRESS = "InProgress"
    PREPARING = "Preparing"
    QUEUED = "Queued"
    UNKNOWN = "Unknown"
    CANCELLED = "Cancelled"
    CANCELING = "Canceling"

class ExecutorNodeSize(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The node size to use per executor.
    """

    NONE = "None"
    SMALL = "Small"
    MEDIUM = "Medium"
    LARGE = "Large"
    X_LARGE = "XLarge"
    XX_LARGE = "XXLarge"
    XXX_LARGE = "XXXLarge"

class Family(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Family of constrained resource.
    """

    COMPUTE = "Compute"
    STORAGE = "Storage"

class InvitationStatus(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The status of the invitation.
    """

    PENDING = "Pending"
    REJECTED = "Rejected"
    ACCEPTED = "Accepted"

class Kind(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Kind of constrained resource.
    """

    SYNAPSE_SPARK_POOL = "SynapseSparkPool"
    SCRIPT = "Script"
    LOCATION = "Location"
    BLOB = "Blob"
    CONTAINER = "Container"
    BLOB_FOLDER = "BlobFolder"
    ADLS_GEN2_FILE_SYSTEM = "AdlsGen2FileSystem"
    ADLS_GEN2_FOLDER = "AdlsGen2Folder"
    ADLS_GEN2_FILE = "AdlsGen2File"
    SYNAPSE_SPARK = "SynapseSpark"
    DATA_MOVEMENT = "DataMovement"
    SCRIPT_EXECUTION = "ScriptExecution"
    DIAGNOSTIC_LEVEL = "DiagnosticLevel"
    DATA_ASSET = "DataAsset"
    DATA_ASSET_REFERENCE = "DataAssetReference"
    SCRIPT_REFERENCE = "ScriptReference"

class Language(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The script language
    """

    PYTHON = "Python"

class LastModifiedByType(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The type of identity that last modified the resource.
    """

    USER = "User"
    APPLICATION = "Application"
    MANAGED_IDENTITY = "ManagedIdentity"
    KEY = "Key"

class LogLevel(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The policy log level.
    """

    VERBOSE = "Verbose"
    INFORMATION = "Information"
    WARNING = "Warning"
    ERROR = "Error"
    CRITICAL = "Critical"

class NodeSize(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Gets or sets the level of compute power that each node in the Synapse Spark pool has.
    """

    NONE = "None"
    SMALL = "Small"
    MEDIUM = "Medium"
    LARGE = "Large"
    X_LARGE = "XLarge"
    XX_LARGE = "XXLarge"
    XXX_LARGE = "XXXLarge"

class NodeSizeFamily(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Gets or sets the kind of nodes that the Big Data pool provides.
    """

    NONE = "None"
    MEMORY_OPTIMIZED = "MemoryOptimized"

class PipelineRunMode(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Mode of pipeline run used.
    """

    PRODUCTION = "Production"
    TEST = "Test"

class PipelineRunStatus(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Pipeline run status
    """

    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    IN_PROGRESS = "InProgress"
    PREPARING = "Preparing"
    QUEUED = "Queued"
    UNKNOWN = "Unknown"
    CANCELLED = "Cancelled"
    CANCELING = "Canceling"

class PipelineStepRunStatus(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Pipeline step run status
    """

    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    IN_PROGRESS = "InProgress"
    PREPARING = "Preparing"
    QUEUED = "Queued"
    UNKNOWN = "Unknown"
    CANCELLED = "Cancelled"
    CANCELING = "Canceling"

class ProposalApprovalStatus(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Current approval status
    """

    PENDING = "Pending"
    APPROVED = "Approved"
    EXPIRED = "Expired"

class ProvisioningState(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Provisioning state of the DataAsset
    """

    SUCCEEDED = "Succeeded"
    CREATING = "Creating"
    UPDATING = "Updating"
    DELETING = "Deleting"
    MOVING = "Moving"
    FAILED = "Failed"

class ResourceType(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The type of resourced used by the entitlement.
    """

    DATA_ASSET_REFERENCE = "DataAssetReference"
    SCRIPT_REFERENCE = "ScriptReference"

class ScriptKind(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Kind of the referenced script.
    """

    SYNAPSE_SPARK = "SynapseSpark"

class ScriptVisibility(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """The referenced script visibility modifier.
    """

    SHOW_ALL = "ShowAll"
    HIDDEN_CONTENT = "HiddenContent"

class Status(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Operation state of the long running operation.
    """

    ACCEPTED = "Accepted"
    IN_PROGRESS = "InProgress"
    TRANSIENT_FAILURE = "TransientFailure"
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    CANCELED = "Canceled"

class Type(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Identity Type
    """

    SYSTEM_ASSIGNED = "SystemAssigned"

class Visibility(with_metaclass(_CaseInsensitiveEnumMeta, str, Enum)):
    """Script visibility mode
    """

    SHOW_ALL = "ShowAll"
    HIDDEN_CONTENT = "HiddenContent"
