# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------


from .. import try_manual


# EXAMPLE: /Pipelines/put/Create an Azure pipeline to deploy a sample ASP.Net application to Azure web-app
@try_manual
def step_pipeline_create(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az devops pipeline create '
             '--location "South India" '
             '--properties bootstrapConfiguration={{"template":{{"id":"ms.vss-continuous-delivery-pipeline-templates.as'
             'pnet-windowswebapp","parameters":{{"appInsightLocation":"South India","appServicePlan":"S1 '
             'Standard","azureAuth":"{{\\"scheme\\":\\"ServicePrincipal\\",\\"parameters\\":{{\\"tenantid\\":\\"{{subsc'
             'riptionTenantId}}\\",\\"objectid\\":\\"{{appObjectId}}\\",\\"serviceprincipalid\\":\\"{{appId}}\\",\\"ser'
             'viceprincipalkey\\":\\"{{appSecret}}\\"}}}}","location":"South India","resourceGroup":"myAspNetWebAppPipe'
             'line-rg","subscriptionId":"{{subscriptionId}}","webAppName":"myAspNetWebApp"}}}}}} '
             'organization={{"name":"myAspNetWebAppPipeline-org"}} project={{"name":"myAspNetWebAppPipeline-project"}} '
             ''
             '--pipeline-name "{myPipeline}" '
             '--resource-group "{rg}"',
             checks=checks)


# EXAMPLE: /Pipelines/get/Get an existing Azure pipeline
@try_manual
def step_pipeline_show(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az devops pipeline show '
             '--name "{myPipeline}" '
             '--resource-group "{rg}"',
             checks=checks)


# EXAMPLE: /Pipelines/get/List all Azure Pipelines under the specified resource group
@try_manual
def step_pipeline_list(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az devops pipeline list '
             '--resource-group "{rg}"',
             checks=checks)


# EXAMPLE: /Pipelines/get/List all Azure pipelines under the specified subscription
@try_manual
def step_pipeline_list2(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az devops pipeline list '
             '-g ""',
             checks=checks)


# EXAMPLE: /Pipelines/patch/Get an existing Azure pipeline
@try_manual
def step_pipeline_update(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az devops pipeline update '
             '--name "{myPipeline}" '
             '--resource-group "{rg}" '
             '--tags tagKey="tagvalue"',
             checks=checks)


# EXAMPLE: /Pipelines/delete/Get an existing Azure pipeline
@try_manual
def step_pipeline_delete(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az devops pipeline delete -y '
             '--name "{myPipeline}" '
             '--resource-group "{rg}"',
             checks=checks)


# EXAMPLE: /PipelineTemplateDefinitions/get/Get the list of pipeline template definitions
@try_manual
def step_pipeline_template_definition_list(test, rg, checks=None):
    if checks is None:
        checks = []
    test.cmd('az devops pipeline-template-definition list',
             checks=checks)

